use axum::{
    routing::{get, post, put},
    Router,
};

use crate::handler::novel_handler;
use crate::state::user_state::UserState;

pub fn internal_routes() -> Router<UserState> {
    Router::new().route("/callback", post(novel_handler::ingest_worker_callback))
}

pub fn routes() -> Router<UserState> {
    Router::new()
        .route(
            "/projects",
            post(novel_handler::create_project).get(novel_handler::list_projects),
        )
        .route(
            "/projects/:project_id",
            get(novel_handler::get_project)
                .delete(novel_handler::delete_project)
                .patch(novel_handler::update_project),
        )
        .route(
            "/projects/:project_id/cancel",
            post(novel_handler::cancel_project),
        )
        .route(
            "/projects/:project_id/config-snapshots",
            get(novel_handler::list_config_snapshots).post(novel_handler::create_config_snapshot),
        )
        .route(
            "/projects/:project_id/config-snapshots/:snapshot_id/activate",
            post(novel_handler::activate_config_snapshot),
        )
        .route(
            "/llm-profiles",
            get(novel_handler::list_llm_profiles).post(novel_handler::create_llm_profile),
        )
        .route(
            "/llm-profiles/:id",
            put(novel_handler::update_llm_profile).delete(novel_handler::delete_llm_profile),
        )
        .route(
            "/llm-profiles/:id/test",
            post(novel_handler::test_llm_profile),
        )
        .route(
            "/embedding-profiles",
            get(novel_handler::list_embedding_profiles)
                .post(novel_handler::create_embedding_profile),
        )
        .route(
            "/embedding-profiles/:id",
            put(novel_handler::update_embedding_profile)
                .delete(novel_handler::delete_embedding_profile),
        )
        .route(
            "/embedding-profiles/:id/test",
            post(novel_handler::test_embedding_profile),
        )
        .route(
            "/projects/:project_id/architecture/generate",
            post(novel_handler::generate_architecture),
        )
        .route(
            "/projects/:project_id/architecture",
            get(novel_handler::get_architecture).put(novel_handler::update_architecture),
        )
        .route(
            "/projects/:project_id/character-state",
            get(novel_handler::get_character_state).put(novel_handler::update_character_state),
        )
        .route(
            "/projects/:project_id/global-summary",
            get(novel_handler::get_global_summary).put(novel_handler::update_global_summary),
        )
        .route(
            "/projects/:project_id/plot-arcs",
            get(novel_handler::get_plot_arcs).put(novel_handler::update_plot_arcs),
        )
        .route(
            "/projects/:project_id/blueprint/generate",
            post(novel_handler::generate_blueprint),
        )
        .route(
            "/projects/:project_id/blueprint/chapters/:chapter_number",
            get(novel_handler::get_blueprint_chapter).put(novel_handler::update_blueprint_chapter),
        )
        .route(
            "/projects/:project_id/blueprint/chapters",
            get(novel_handler::list_blueprint_chapters),
        )
        .route(
            "/projects/:project_id/blueprint",
            get(novel_handler::get_blueprint).put(novel_handler::update_blueprint),
        )
        .route(
            "/projects/:project_id/chapters/:chapter_number/prompt/build",
            post(novel_handler::build_chapter_prompt),
        )
        .route(
            "/projects/:project_id/chapters/:chapter_number/prompt",
            get(novel_handler::get_chapter_prompt).put(novel_handler::update_chapter_prompt),
        )
        .route(
            "/projects/:project_id/chapters/batch-generate",
            post(novel_handler::batch_generate_chapters),
        )
        .route(
            "/projects/:project_id/chapters/:chapter_number/draft/generate",
            post(novel_handler::generate_chapter_draft),
        )
        .route(
            "/projects/:project_id/chapters/:chapter_number/enrich",
            post(novel_handler::enrich_chapter),
        )
        .route(
            "/projects/:project_id/chapters/:chapter_number/finalize",
            post(novel_handler::finalize_chapter),
        )
        .route(
            "/projects/:project_id/chapters/:chapter_number/consistency-checks/latest",
            get(novel_handler::get_latest_consistency_check),
        )
        .route(
            "/projects/:project_id/chapters/:chapter_number/consistency-checks",
            get(novel_handler::list_consistency_checks)
                .post(novel_handler::create_consistency_check),
        )
        .route(
            "/projects/:project_id/chapters/:chapter_number",
            get(novel_handler::get_chapter).put(novel_handler::update_chapter),
        )
        .route(
            "/projects/:project_id/chapters",
            get(novel_handler::list_chapters),
        )
        .route(
            "/projects/:project_id/knowledge/imports",
            get(novel_handler::list_knowledge_imports).post(novel_handler::import_knowledge),
        )
        .route(
            "/projects/:project_id/knowledge/chunks",
            get(novel_handler::list_knowledge_chunks),
        )
        .route(
            "/projects/:project_id/memory/clear",
            post(novel_handler::clear_memory),
        )
        .route(
            "/projects/:project_id/jobs/:job_id/retry",
            post(novel_handler::retry_job),
        )
        .route(
            "/projects/:project_id/jobs/:job_id",
            get(novel_handler::get_job),
        )
        .route("/projects/:project_id/jobs", get(novel_handler::list_jobs))
        .route(
            "/projects/:project_id/events",
            get(novel_handler::list_events),
        )
}
