use super::auth;
use crate::config::database::Database;
use crate::middleware::auth as auth_middleware;
use crate::middleware::charging;
use crate::routes::{register, user};
use crate::state::auth_state::AuthState;
// use crate::state::token_state::TokenState;
use crate::state::user_state::UserState;
use axum::routing::get;
use axum::{middleware, Router};
use std::sync::Arc;
use tower::ServiceBuilder;
use tower_http::trace::TraceLayer;

pub fn routes(db_conn: Arc<Database>) -> Router {
    let merged_router = {
        let auth_state = AuthState::new(&db_conn);
        let user_state = UserState::new(&db_conn);

        // /api/v1
        Router::new()
            .nest(
                "/auth",
                auth::routes()
                    .with_state(auth_state)
                    .merge(register::routes().with_state(user_state.clone())),
            )
            .nest(
                "/user",
                user::routes()
                    .layer(
                        ServiceBuilder::new()
                            .layer(middleware::from_fn_with_state(
                                user_state.clone(),
                                auth_middleware::auth,
                            ))
                            .layer(axum::Extension(user_state.clone())),
                    )
                    .with_state(user_state.clone()),
            )
            .nest(
                "/campaigns",
                crate::routes::campaign::routes()
                    .layer(
                        ServiceBuilder::new()
                            .layer(middleware::from_fn_with_state(
                                user_state.clone(),
                                auth_middleware::auth,
                            ))
                            .layer(axum::Extension(user_state.campaign_service.clone()))
                            .layer(axum::Extension(user_state.agent_service.clone()))
                            .layer(axum::Extension(user_state.clone())),
                    )
                    .with_state(user_state.clone()),
            )
            .merge(
                crate::routes::template::routes()
                    .layer(
                        ServiceBuilder::new()
                            .layer(middleware::from_fn_with_state(
                                user_state.clone(),
                                auth_middleware::auth,
                            ))
                            .layer(axum::Extension(user_state.clone())),
                    )
                    .with_state(user_state.clone()),
            )
            .nest(
                "/config",
                crate::routes::config::routes()
                    .layer(axum::Extension(user_state.platform_service.clone()))
                    .layer(axum::Extension(user_state.config_service.clone()))
                    .with_state(user_state.clone()),
            )
            .nest(
                "/wallet",
                crate::routes::wallet::routes()
                    .layer(
                        ServiceBuilder::new()
                            .layer(middleware::from_fn_with_state(
                                user_state.clone(),
                                auth_middleware::auth,
                            ))
                            .layer(axum::Extension(user_state.clone())),
                    )
                    .with_state(user_state.clone()),
            )
            .nest(
                "/promo-codes",
                crate::routes::promo_code::promo_code_routes(Arc::new(
                    user_state.promo_code_service.clone(),
                ))
                .layer(
                    ServiceBuilder::new()
                        .layer(middleware::from_fn_with_state(
                            user_state.clone(),
                            auth_middleware::auth,
                        ))
                        .layer(axum::Extension(user_state.clone())),
                ),
            )
            .nest(
                "/accounts",
                crate::routes::social_account::routes()
                    .layer(
                        ServiceBuilder::new()
                            .layer(middleware::from_fn_with_state(
                                user_state.clone(),
                                auth_middleware::auth,
                            ))
                            .layer(axum::Extension(user_state.clone())),
                    )
                    .with_state(user_state.clone()),
            )
            .nest(
                "/social-groups",
                crate::routes::social_group::routes()
                    .layer(
                        ServiceBuilder::new()
                            .layer(middleware::from_fn_with_state(
                                user_state.clone(),
                                auth_middleware::auth,
                            ))
                            .layer(axum::Extension(user_state.clone())),
                    )
                    .with_state(user_state.clone()),
            )
            .nest(
                "/stats",
                crate::routes::dashboard::routes()
                    .layer(
                        ServiceBuilder::new()
                            .layer(middleware::from_fn_with_state(
                                user_state.clone(),
                                auth_middleware::auth,
                            ))
                            .layer(axum::Extension(user_state.clone())),
                    )
                    .with_state(user_state.clone()),
            )
            .nest(
                "/ai",
                crate::routes::ai::routes()
                    .layer(
                        ServiceBuilder::new()
                            .layer(middleware::from_fn_with_state(
                                user_state.clone(),
                                auth_middleware::auth,
                            ))
                            .layer(middleware::from_fn_with_state(
                                user_state.clone(),
                                charging::charging_middleware,
                            ))
                            .layer(axum::Extension(user_state.clone())),
                    )
                    .with_state(user_state.clone()),
            )
            .nest(
                "/agent",
                crate::routes::agent_analysis::routes()
                    .layer(
                        ServiceBuilder::new()
                            .layer(middleware::from_fn_with_state(
                                user_state.clone(),
                                auth_middleware::auth,
                            ))
                            .layer(middleware::from_fn_with_state(
                                user_state.clone(),
                                charging::charging_middleware,
                            ))
                            .layer(axum::Extension(user_state.clone())),
                    )
                    .with_state(user_state.clone()),
            )
            .nest(
                "/crawler-tasks",
                crate::routes::crawler::routes()
                    .layer(
                        ServiceBuilder::new()
                            .layer(middleware::from_fn_with_state(
                                user_state.clone(),
                                auth_middleware::auth,
                            ))
                            .layer(axum::Extension(user_state.clone())),
                    )
                    .with_state(user_state.clone()),
            )
            .nest(
                "/agent",
                crate::routes::agent::routes(user_state.clone()).layer(
                    ServiceBuilder::new()
                        .layer(middleware::from_fn_with_state(
                            user_state.clone(),
                            auth_middleware::auth,
                        ))
                        .layer(axum::Extension(user_state.clone())),
                ),
            )
            .nest(
                "/video",
                crate::routes::video::video_routes()
                    .layer(
                        ServiceBuilder::new()
                            .layer(middleware::from_fn_with_state(
                                user_state.clone(),
                                auth_middleware::auth,
                            ))
                            .layer(middleware::from_fn_with_state(
                                user_state.clone(),
                                charging::charging_middleware,
                            ))
                            .layer(axum::Extension(user_state.clone())),
                    )
                    .with_state(user_state.clone()),
            )
            .nest(
                "/scan",
                crate::routes::scan::routes()
                    .layer(
                        ServiceBuilder::new()
                            .layer(middleware::from_fn_with_state(
                                user_state.clone(),
                                auth_middleware::auth,
                            ))
                            .layer(middleware::from_fn_with_state(
                                user_state.clone(),
                                charging::charging_middleware,
                            ))
                            .layer(axum::Extension(user_state.clone())),
                    )
                    .with_state(user_state.clone()),
            )
            .nest(
                "/public",
                crate::routes::public::public_routes(&user_state).with_state(user_state.clone()),
            )
            .nest(
                "/upload-tasks",
                crate::routes::upload_task::routes()
                    .layer(
                        ServiceBuilder::new()
                            .layer(middleware::from_fn_with_state(
                                user_state.clone(),
                                auth_middleware::auth,
                            ))
                            .layer(axum::Extension(user_state.clone())),
                    )
                    .with_state(user_state.clone()),
            )
            .nest(
                "/notifications",
                crate::routes::notification::notification_routes(db_conn.clone())
                    .layer(
                        ServiceBuilder::new()
                            .layer(middleware::from_fn_with_state(
                                user_state.clone(),
                                auth_middleware::auth,
                            ))
                            .layer(axum::Extension(user_state.clone())),
                    ),
            )
            .merge(Router::new().route("/health", get(|| async { "Healthy..." })))
    };

    Router::new()
        .nest("/api/v1", merged_router)
        .layer(TraceLayer::new_for_http())
}
