version: "3.8"

services:
  backend:
    build:
      context: ../..
      dockerfile: Dockerfile.api
      cache_from:
        - aihub_backend:latest
      args:
        BUILDKIT_INLINE_CACHE: 1
    image: aihub_backend:latest
    container_name: aihub_backend
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
