//! GlanceMind Database - Centralized Schema and Migration Management
//!
//! This crate provides:
//! - Database schema definitions (auto-generated by Diesel)
//! - Entity definitions (Diesel ORM models)
//! - Migration management
//! - Database connection utilities

use diesel::pg::PgConnection;
use diesel::prelude::*;
use diesel::r2d2::{self, ConnectionManager};
use std::env;

pub mod entity;
pub mod schema;

// Re-export all entities at crate root for convenience
pub use entity::*;

/// Database connection pool type
pub type DbPool = r2d2::Pool<ConnectionManager<PgConnection>>;

/// Embed migrations at compile time
pub const MIGRATIONS: diesel_migrations::EmbeddedMigrations = diesel_migrations::embed_migrations!();

/// Establish a single database connection
pub fn establish_connection() -> PgConnection {
    let database_url = env::var("DATABASE_URL").expect("DATABASE_URL must be set");
    PgConnection::establish(&database_url)
        .unwrap_or_else(|_| panic!("Error connecting to {}", database_url))
}

/// Create a database connection pool
pub fn create_pool() -> DbPool {
    let database_url = env::var("DATABASE_URL").expect("DATABASE_URL must be set");
    let manager = ConnectionManager::<PgConnection>::new(database_url);
    r2d2::Pool::builder()
        .max_size(10)
        .build(manager)
        .expect("Failed to create pool")
}

/// Run pending migrations
pub fn run_migrations(conn: &mut PgConnection) -> Result<(), Box<dyn std::error::Error + Send + Sync + 'static>> {
    use diesel_migrations::MigrationHarness;
    conn.run_pending_migrations(MIGRATIONS)?;
    Ok(())
}
